### ISSUE TITLE
Default Fragment

### ISSUE THREAD

**Issue by hemant2705** [CSwala/CSwala-android#102]
Currently when app is opening their is no fragment shown and after clicking menu items it is showing the fragment content respectively.
setting a default fragment can help .
We can put explore fragment as our Default fragment and when app will restart we can it will open the explore fragment .

please assign this to me by adding tags accordingly

**Comment by riturajjain2000** [comment]
Ok make the explore frag. as default

**Comment by venkatesh1226** [comment]
I want to work on it if possible.

**Comment by hemant2705** [comment]
I have already finished doing this task.
just resolving the conflicts .
give me a day or two ,then you can proceed ahead.
