### ISSUE TITLE
UI Enhancement: Navigation Bar

### ISSUE THREAD

**Issue by aditya-190** [CSwala/CSwala-android#104]
We can change the Navigation Bar from ChipNavigation to Meow Navigation (Simple and Curved Navigation Bar with Animated Transitions on Click).

**Check This App** :  https://play.google.com/store/apps/details?id=com.bhardwaj.memento

If you are interested I have done implementing it and can make PR.

@GSSOC'21 Participant

**Comment by riturajjain2000** [comment]
Let the basic functionality of the app be completed , then we can work on enhancing the UI

**Comment by aditya-190** [comment]
Sure

**Comment by aditya-190** [comment]
@riturajjain2000 Should I convert the project to Kotlin???

**Comment by riturajjain2000** [comment]
That can be done after the participants are selected , that's from 1st of April, as most beginners find it difficult to work with kotlin
