### ISSUE TITLE
get the title fixed

### ISSUE THREAD

**Issue by RashikaJoshi-777** [CSwala/CSwala-android#108]
in the logout screen when we click hackfeed the title still shows jobhunt instead of hackfeed . i want to fix this please assign this issue to me (i am GSSOC participant)
![Screenshot_20210321-083606 1](https://user-images.githubusercontent.com/75016031/111895652-13cefa80-8a3a-11eb-8beb-7928b9d9239b.png)

**Comment by riturajjain2000** [comment]
No need to fix this as we'll anyway be removing this when we'll add functioning to it, so no need to fix this !
