### ISSUE TITLE
Check for network strength

### ISSUE THREAD

**Issue by GowthamGoush** [CSwala/CSwala-android#109]
#### ➡️  Add a snack bar to notify.

**Comment by adrishyantee** [comment]
If the issue is not addressed, can I work on this?

**Comment by GowthamGoush** [comment]
Actually, I'm on to this and waiting for the email login feature to be implemented.

**Comment by Khushi-24** [comment]
@riturajjain2000 Is the issue resolved? If not can I work on this?
