### ISSUE TITLE
To add edit profile option

### ISSUE THREAD

**Issue by RashikaJoshi-777** [CSwala/CSwala-android#111]
after the profile fragment is build i want to add edit profile option to the fragment [GSSOC'21]

**Comment by riturajjain2000** [comment]
I'll assign you the issue after the work is done

**Comment by riturajjain2000** [comment]
> after the profile fragment is build i want to add edit profile option to the fragment [GSSOC'21]

Now you can work on it

**Comment by RashikaJoshi-777** [comment]
ok

**Comment by SanjayDevTech** [comment]
Can I also work in this issue
