### ISSUE TITLE
Adding calendar feature for CP

### ISSUE THREAD

**Issue by RashikaJoshi-777** [CSwala/CSwala-android#112]
As this app is to Get Latest Updates about Everything there exits in Computer Science, it will be good to add a feature with a calendar which shows all the contest from different websites (such as codeforces, codechef etc.) which will occur in upcoming dates and also shows which all contest a user attempted and which all a user missed also a reminder can be set for a contest (if user wants).      
please assign this issue to me

**Comment by ddvader44** [comment]
good idea, where will you be adding all of this?

**Comment by riturajjain2000** [comment]
any idea how are you going to implement this?

**Comment by RashikaJoshi-777** [comment]
> good idea, where will you be adding all of this?

after the profile fragment we can add a another fragment for contest which includes all this information

**Comment by RashikaJoshi-777** [comment]
> any idea how are you going to implement this?
In the fragment there will be a calendar which will show number of contest on each date . On clicking on the specific date we will have all the details of all the contests like which website is organizing the contest, it's timing  and a button to add reminder of the contest in which user is interested also in case user miss the contest user will get to know what all contest user missed.

**Comment by RashikaJoshi-777** [comment]
please assign this to me

**Comment by ddvader44** [comment]
go ahead @RashikaJoshi-777

**Comment by riturajjain2000** [comment]
I think this feature should be under the Hackfeed fragment only
use 2 tabs , One for the news and the second for Events

**Comment by Khushi-24** [comment]
@RashikaJoshi-777  Are you still working on this issue?

**Comment by RashikaJoshi-777** [comment]
> @RashikaJoshi-777 Are you still working on this issue?

i was working on implementing edit profile feature and that completed yesterday only and now i am having exams so i will come to this issue after my exams get over
