### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [CSwala/CSwala-android#113]
Hi ! I would like to create a file named contributing.md which will
Add the following -

1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
I would like to work on this as a part of GSSOC'21

**Comment by ddvader44** [comment]
modify the existing contributing.md and raise a pr

**Comment by khareyash05** [comment]
@ddvader44 I have to merge it in develop branch or main?

**Comment by khareyash05** [comment]
@ddvader44 Attached a PR Have a look!
