### ISSUE TITLE
Implement the Tech Data/Resources Activity.

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/CSwala-android#117]
Implement the Data Activity. It consists of the resources from the DB.
**Before taking the issue, discuss your implementation idea on the Discord Server**

**Comment by ANUJAGRAWAL2000** [comment]
Hey @riturajjain2000 I want to contribute to this project. Can u please describe this in more detail like what we have to do in this?

**Comment by riturajjain2000** [comment]
Discuss on Discord Server 
As The other participants can give ideas that we may skip here

**Comment by ANUJAGRAWAL2000** [comment]
Sure

**Comment by ANUJAGRAWAL2000** [comment]
@riturajjain2000 I want to work on this issue I have discuss on discord about this issue.
