### ISSUE TITLE
Add enter animation for recyclerview of Explore fragment

### ISSUE THREAD

**Issue by GowthamGoush** [CSwala/CSwala-android#124]
✔️ Implement enter animation to items of the recycler view.
✔️ Add slide/fall animation to these items.
✔️ Animation occurs on switching to Explore fragment.
✔️ It intensifies the user interface.

**Comment by rohittrimalle** [comment]
i can work on this issue

**Comment by riturajjain2000** [comment]
do you want to work on this @GowthamGoush , or should I assign this to @rohittrimalle ?

**Comment by GowthamGoush** [comment]
Oops! Actually, I started working on it
