### ISSUE TITLE
android.app.ProgressDialog' is deprecated as of API 26

### ISSUE THREAD

**Issue by vipozdn** [CSwala/CSwala-android#13]
android.app.ProgressDialog' is deprecated as of API 26
Class: LoginActivity

So it's better to use [ProgressBar](https://developer.android.com/reference/android/widget/ProgressBar)

PS i'm interested in fixing this issue
![issue_cr](https://user-images.githubusercontent.com/32436953/109175851-45d0a200-7797-11eb-8dab-9c0681c41910.png)

**Comment by riturajjain2000** [comment]
Go ahead ! I'll assign it to you as soon as GSSOC begins

**Comment by jatinjain29** [comment]
@riturajjain2000 @vipozdn 
Hello, I am a GSSOC participant and would like to work on this issue. Could you please assign it to me?

**Comment by riturajjain2000** [comment]
> @riturajjain2000 @vipozdn
> Hello, I am a GSSOC participant and would like to work on this issue. Could you please assign it to me?

Go ahead !
