### ISSUE TITLE
Google login not working 

### ISSUE THREAD

**Issue by hagerk720** [CSwala/CSwala-android#133]
nothing happen after login

**Comment by GowthamGoush** [comment]
Hey, @hagerk720, you have to share your SHA1 key with the project maintainer @riturajjain2000, and it will work perfectly once you do this.

**Comment by hagerk720** [comment]
sorry put what you meaning of SHA1 ?

**Comment by GowthamGoush** [comment]
SHA-1 fingerprint is a unique key generated for your PC that can be used for signing. You can find this unique key in your android studio.
