### ISSUE TITLE
Enhancement of UI/UX in Hackfeed and providing swipe feature.

### ISSUE THREAD

**Issue by viralkumar28** [CSwala/CSwala-android#139]
- Read more and the time given is overlapping, needs improvement.
-  I will provide swipe feature in between both the tabs Latest News and Events.
![new](https://user-images.githubusercontent.com/55316718/113103460-eeea3c80-921c-11eb-9a95-67d16659a1bf.jpg)

**Comment by deepsjuneja** [comment]
Can I work on this issue?

**Comment by riturajjain2000** [comment]
I have assigned @viralkumar28 also as he completed work on one part of the issue
