### ISSUE TITLE
Problem in profile fragment 

### ISSUE THREAD

**Issue by hagerk720** [CSwala/CSwala-android#143]
The whole page of profile fragment does't appere and does't scroll 
Please assign this issue to me (gssoc 21) 
![Screenshot_20210331-213333_CS wala](https://user-images.githubusercontent.com/78926069/113201362-b3c22a80-9269-11eb-99a0-bc091976b9d5.jpg)

**Comment by ddvader44** [comment]
go ahead @hagerk720
