### ISSUE TITLE
Add a dialog to confirm exit

### ISSUE THREAD

**Issue by GowthamGoush** [CSwala/CSwala-android#144]
💠 Generally, on back pressed, the application exits to the mobile home screen.
💠 Sometimes, this might deprive the user experience if the user presses the back key accidentally.
💠 Therefore, it is wise to seek confirmation before exiting the app on back pressed with either a dialog or a toast.

**Comment by deepsjuneja** [comment]
Can I work on this issue?

**Comment by GowthamGoush** [comment]
I'm working on this
