### ISSUE TITLE
The package name is repeated

### ISSUE THREAD

**Issue by vipozdn** [CSwala/CSwala-android#15]
Your package name is repeated.
I suggest calling it com.cswala.appname
This is the standard naming convention for java packages. The first is com. Then the developer's name. Then the application name.
[Link for more info](https://stackoverflow.com/a/6273935/9972209)

**Comment by riturajjain2000** [comment]
Go ahead and change it to `com.cswala.android`  ! I'll assign it to you as soon as GSSOC begins

**Comment by riturajjain2000** [comment]
Thanks for raising the issue , I'll fix it as it is connected to the database also !!
