### ISSUE TITLE
Fix data fetch issue

### ISSUE THREAD

**Issue by GowthamGoush** [CSwala/CSwala-android#157]
- Toast pops up when data fetch fails.
- One of the reason could be "Resource exhaustion" in Firebase.  
<div align = "center">
<img src="https://user-images.githubusercontent.com/63305824/114432275-21614580-9bde-11eb-98e4-b484298b8cf3.png" width="200" height="400" />
</div>

**Comment by ddvader44** [comment]
How are you planning to improve/fix this?

**Comment by GowthamGoush** [comment]
I don't think this could be solved by a participant since this issue seems to be from firebase.

**Comment by ddvader44** [comment]
@riturajjain2000 can you please look into this?

**Comment by riturajjain2000** [comment]
I'll check
