### ISSUE TITLE
Add News Fragment

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/CSwala-android#16]
Add a blank fragment for this item, just as to provide the functionality of swapping screens as of now. Will add features later.

**Comment by KapilYadav-dev** [comment]
I'll do this, Please assign this issue in GSSOC'21.

**Comment by kunal299** [comment]
@riturajjain2000 I would love to contribute to this issue. Could you plz assign this issue to me?

**Comment by riturajjain2000** [comment]
@KapilYadav-dev @kunal299 Thanks for showing interest in this issue!
Let GSSOC begins and once I get to know the list of accepted participants for this project, I'll assign this issue accordingly.

**Comment by viralkumar28** [comment]
I can do this, can you assign this to me??

**Comment by riturajjain2000** [comment]
@viralkumar28 Thanks for showing interest in this issue!
Let GSSOC begins and once I get to know the list of accepted participants for this project, I'll assign this issue accordingly.

**Comment by MukulKolpe** [comment]
Hey @riturajjain2000 , can you please assign this issue to me, If @kunal299 is not working on it??

**Comment by kunal299** [comment]
@MukulKolpe I m working on this issue.

**Comment by MukulKolpe** [comment]
Okay!! @kunal299

**Comment by adiig7** [comment]
@kunal299 bro have you done it? If not, may I take up this one?

**Comment by kunal299** [comment]
@adiig7 Yes, little bit left.

**Comment by viralkumar28** [comment]
Hey, I want to work on this issue.

**Comment by kunal299** [comment]
@riturajjain2000 Hey I'm done with it.

**Comment by riturajjain2000** [comment]
then send PR

**Comment by kunal299** [comment]
@riturajjain2000 give me 5 min
