### ISSUE TITLE
Add Pagination

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/CSwala-android#168]
Add Pagination to recycler views wherever required

**Comment by GowthamGoush** [comment]
I would like to work on this.

**Comment by deepsjuneja** [comment]
Can I work on this issue?

**Comment by ddvader44** [comment]
@deepsjuneja what's the progress?

**Comment by deepsjuneja** [comment]
> @deepsjuneja what's the progress?

I'm working on it. Hopefully, I'll generate the PR within a couple of days.
