### ISSUE TITLE
dependencies should be updated

### ISSUE THREAD

**Issue by vipozdn** [CSwala/CSwala-android#18]
Some dependencies in build.gradle (module: app) and in build.gradle (project level) should be updated

module: app
A newer version of com.google.android.gms:play-services-base than 17.5.0 is available: 17.6.0
A newer version of com.google.android.gms:play-services-location than 17.1.0 is available: 18.0.0
A newer version of com.google.firebase:firebase-firestore than 22.0.2 is available: 22.1.0
Plugin version (null) is not the same as library version (1.4.21) - [check this link to fix this warning](https://stackoverflow.com/questions/49956051/warning-kotlin-plugin-version-is-not-the-same-as-library-version-but-it-is)

project level
A newer version of com.android.tools.build:gradle than 4.0.2 is available: 4.1.2
A newer version of com.google.gms:google-services than 4.3.4 is available: 4.3.5

**Comment by riturajjain2000** [comment]
Ok go ahead ! I'll assign it to you as soon as GSSOC begins!

**Comment by viralkumar28** [comment]
I would like to contribute, could you assign this to me??

**Comment by riturajjain2000** [comment]
@viralkumar28 Thanks for showing interest in this issue!
Let GSSOC begins and once I get to know the list of accepted participants for this project, I'll assign this issue accordingly.

**Comment by GowthamGoush** [comment]
May I work on this issue?

**Comment by riturajjain2000** [comment]
> May I work on this issue?

sure
go ahead!
