### ISSUE TITLE
Add Content to Onboarding Screens

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/CSwala-android#180]
The Onboarding Screens are to be updated with Proper Details and Description

**Comment by Khushi-24** [comment]
@riturajjain2000 Can I work on this issue?

**Comment by gargijs** [comment]
I want to work on this.

**Comment by ddvader44** [comment]
@Khushi-24 what's the progress?

**Comment by Khushi-24** [comment]
@ddvader44 Yes I am on it. It will be completed by tomorrow.

**Comment by Khushi-24** [comment]
@ddvader44 @riturajjain2000 Please review it.
