### ISSUE TITLE
idea files got into the project

### ISSUE THREAD

**Issue by vipozdn** [CSwala/CSwala-android#19]
add .idea/ to .gitignore file
[link](https://stackoverflow.com/a/39539084/9972209)
![issue_cr](https://user-images.githubusercontent.com/32436953/109276352-f8037a80-7826-11eb-8f3e-63df943136d9.png)

**Comment by riturajjain2000** [comment]
Ok go ahead ! I'll assign it to you as soon as GSSOC begins!

**Comment by jonathanalvares9009** [comment]
Can I do this?

**Comment by riturajjain2000** [comment]
> Can I do this?

sure , go ahead!

**Comment by jonathanalvares9009** [comment]
Sir made the changes
