### ISSUE TITLE
Remove warning signs so that it does not overlap visibility toggle

### ISSUE THREAD

**Issue by nidhisingh-1** [CSwala/CSwala-android#194]
Shifting the warning signs/message below text-
input so that the warning sign does not overlap with password visibility toggle
<img src = "https://user-images.githubusercontent.com/61702147/121785629-6e5e9980-cbd8-11eb-9f53-cc5ee643981c.jpg" height= 400px width =200>

**Comment by nidhisingh-1** [comment]
Can I work on this issue?

**Comment by riturajjain2000** [comment]
Email Login Screen is no longer a part of the app

**Comment by nidhisingh-1** [comment]
Okay! Got it.
