### ISSUE TITLE
com.google.android.gms.common.api.ApiException: 10: 

### ISSUE THREAD

**Issue by vipozdn** [CSwala/CSwala-android#20]
Google sign in failed
**Probable reason:** you didn't add SHA certificate fingerprints to firebase console
[check this link for details](https://stackoverflow.com/a/49800546/9972209)

**logcat details**
com.google.android.gms.common.api.ApiException: 10: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.5.0:4)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(com.google.android.gms:play-services-auth@@19.0.0:9)
        at com.cswala.cswala.LoginActivity.onActivityResult(LoginActivity.java:149)

**Comment by riturajjain2000** [comment]
It's already there! There must be some other reason!

**Comment by vipozdn** [comment]
1. Did you create new OAuth Client ID to API Console?

This status code means that you are providing unknown server client id. In https://console.developers.google.com/apis/credentials in your project you might need to generate: OAuth client ID -> android and use this client id in your Android app.

2. After adding sha1 certificate to firebase project you should update your google-services.json file in Android project.
3. You have to add both: debug SHA-1, SHA-2 and release SHA-1, SHA-2 (if u've added only release certificates, your debug-build google auth will not work)

**Comment by riturajjain2000** [comment]
>Did you create new OAuth Client ID to API Console?

I tried adding it after you told me to , but it told that the SHA-1 key is already connected to another id , meaning its already there .

**Comment by riturajjain2000** [comment]
>After adding sha1 certificate to firebase project you should update your google-services.json file in Android project.
You have to add both: debug SHA-1, SHA-2 and release SHA-1, SHA-2 (if u've added only release certificates, your debug-build google auth will not work)

Updated json file only is added. So this is because of something  else
