### ISSUE TITLE
Upgrade codebase to  Java 8

### ISSUE THREAD

**Issue by KapilYadav-dev** [CSwala/CSwala-android#22]
Hello @riturajjain2000, we can update codebase to Java 8 so that we can take use of much better functions like Lambda expressions...
If you found this one acceptable then please assign this one to me in GSSOC's

**Comment by riturajjain2000** [comment]
I don't think that's needed as of now as we'll be shifting to kotlin as soon as we get a basic working model.
Still, if you want to work on it, I'll assign it to you!

**Comment by KapilYadav-dev** [comment]
Then this'll be of no use, I guess !!
As we'll be shifting to Kotlin, so I'm closing this issue...
