### ISSUE TITLE
Improvement in Splash Screen

### ISSUE THREAD

**Issue by KapilYadav-dev** [CSwala/CSwala-android#24]
@riturajjain2000  Can we add some cool animation stuff on splash screen rather than lottie animation...
It seems quite awkward, when that lottie animation suddenly shake its hand...

**Comment by riturajjain2000** [comment]
😂😂
Ok go ahead ! I'll assign it to you as soon as GSSOC begins!

**Comment by viralkumar28** [comment]
I am also want to work on this issue.

**Comment by riturajjain2000** [comment]
@viralkumar28 Thanks for showing interest in this issue!
Let GSSOC begins and once I get to know the list of accepted participants for this project, I'll assign this issue accordingly.

**Comment by sakshi2707** [comment]
I want to work on this issue

**Comment by riturajjain2000** [comment]
> I want to work on this issue
sure , go ahead !

**Comment by fin1te** [comment]
I want to try this as well, thanks.

**Comment by rasikabakre** [comment]
I would also like to work on this issue, kindly assign it to me.

**Comment by riturajjain2000** [comment]
@sakshi2707 is working on it , if she's unable to make a PR in 1 day then I'll reassign this.

**Comment by Khushi-24** [comment]
@riturajjain2000 Can I work on this issue?

**Comment by rahulsain** [comment]
Hey , can I work on this?

**Comment by riturajjain2000** [comment]
@Khushi-24 is working on it ,  look other issues to fix
