### ISSUE TITLE
Don't make PR's if the issue is not assigned to you and before the coding period begins!

### ISSUE THREAD

**Issue by vipozdn** [CSwala/CSwala-android#25]
Don't make PR's if the issue is not assigned to you and before the coding period begins!

_Originally posted by @riturajjain2000 in https://github.com/CSwala/CSwala-android/issues/21#issuecomment-787047982_

This is not mentioned in Contributing Guildelines. I think You should add this to  CSwala-android/CONTRIBUTING.md.

**Comment by riturajjain2000** [comment]
> Don't make PR's if the issue is not assigned to you and before the coding period begins!
> 
> _Originally posted by @riturajjain2000 in [#21 (comment)](https://github.com/CSwala/CSwala-android/pull/21#issuecomment-787047982)_
> 
> This is not mentioned in Contributing Guildelines. I think You should add this to CSwala-android/CONTRIBUTING.md.

"Kindly wait for the approval from the maintainers of this project before starting to work on any issue."

It is mentioned there.
