### ISSUE TITLE
Change find ViewById to Binding 

### ISSUE THREAD

**Issue by jonathanalvares9009** [CSwala/CSwala-android#27]
So that it doesn't have to find the view during run time n eventually makes it faster.

**Comment by jonathanalvares9009** [comment]
I would like to work on this issue

**Comment by riturajjain2000** [comment]
I think we should leave this as of now as our app is also having sections like `news` and `job update` and that may need dynamic UI's which is not possible with View Binding

**Comment by jonathanalvares9009** [comment]
Ok sir
