### ISSUE TITLE
Add Explore Fragment

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/CSwala-android#3]
Add a blank fragment for this option, just as to provide the functionality of swapping screens as of now. Will add features later.

**Comment by vipozdn** [comment]
Hello! I can create blank fragment. Should it be opened by default in MainActivity (as we setting explore item by default)?

**Comment by riturajjain2000** [comment]
Yes, you have to add just a blank fragment for now, and, yes it will be the default one!
I'll assign this to you as soon as GSSOC starts!

**Comment by kunal299** [comment]
@riturajjain2000 Can I work on this issue as a part of Gssoc'21?

**Comment by riturajjain2000** [comment]
@kunal299 Thanks for showing interest in this one!
Let GSSOC begins and once I get to know the list of accepted participants for this project, I'll assign this issue accordingly.

**Comment by kunal299** [comment]
@riturajjain2000 sure :)

**Comment by viralkumar28** [comment]
Can you assign this to me?

**Comment by riturajjain2000** [comment]
@viralkumar28 Thanks for showing interest in this issue!
Let GSSOC begins and once I get to know the list of accepted participants for this project, I'll assign this issue accordingly.

**Comment by Anju1415** [comment]
I'm also interested to contribute in this project . can you assign this to me?

**Comment by viralkumar28** [comment]
Hey, I want to work on this issue.
