### ISSUE TITLE
Github login is not working

### ISSUE THREAD

**Issue by jonathanalvares9009** [CSwala/CSwala-android#30]
Sir, I would like to work on this issue

**Comment by riturajjain2000** [comment]
I can assign max. 2 issues to a participant at a time, plz fix other issues to get this assigned to you!

**Comment by adiig7** [comment]
Can i work on this issue?

**Comment by jonathanalvares9009** [comment]
I'm working on this issue

**Comment by adiig7** [comment]
@jonathanalvares9009 Have you done it? If not can i take up this one?

**Comment by fin1te** [comment]
Let me know when this issue is resolved, thanks!

**Comment by adiig7** [comment]
@riturajjain2000 it is been 2 days and the issue hasn't been resolved yet and there isn't any update from @jonathanalvares9009 too. Can i complete this issue?

**Comment by riturajjain2000** [comment]
Wait for 1 more day , If he is still unable to make a PR then I'll reassign it!

**Comment by jonathanalvares9009** [comment]
@riturajjain2000 I have tried for the past two days to implement github authorisation but I'm unable solved it deosn't work completely. You can assign it to @adiig7 I also want to learn how to implement github.

**Comment by adiig7** [comment]
@riturajjain2000 please assign it to me.

**Comment by jonathanalvares9009** [comment]
@adiig7 just start implementing it

**Comment by riturajjain2000** [comment]
> @riturajjain2000 I have tried for the past two days to implement github authorisation but I'm unable solved it deosn't work completely. You can assign it to @adiig7 I also want to learn how to implement github.

ok

**Comment by fin1te** [comment]
Let me try next if the issue is not resolved, Thanks!

**Comment by riturajjain2000** [comment]
sure

**Comment by adiig7** [comment]
@fin1te I'm already on to it.

**Comment by fin1te** [comment]
@adiig7 any updates?

**Comment by fin1te** [comment]
@riturajjain2000  if it is not yet done, can I try this?

**Comment by deepsjuneja** [comment]
Can I work on this issue?

**Comment by deepsjuneja** [comment]
> Can I work on this issue?

@riturajjain2000 you haven't assigned me the issue yet.

**Comment by riturajjain2000** [comment]
done
