### ISSUE TITLE
Strings are hardcoded

### ISSUE THREAD

**Issue by jonathanalvares9009** [CSwala/CSwala-android#31]
I would like to put these strings in strings.xml

**Comment by riturajjain2000** [comment]
I can assign max. 2 issues to a participant at a time, plz fix other issues to get this assigned to you!

**Comment by ritmojs** [comment]
I would like to work on this issue.

**Comment by fin1te** [comment]
I would like to work on this, Please assign this to me, Thanks!

**Comment by ritmojs** [comment]
> I would like to work on this, Please assign this to me, Thanks!

This issue is already assigned to me and I have already made a pull request for this issue.
