### ISSUE TITLE
Add Profile Fragment

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/CSwala-android#4]
Add a blank fragment for this option, just as to provide the functionality of swapping screens as of now. Will add features later.

**Comment by vipozdn** [comment]
Hello! I can create this blank fragment. Should fragment be created in com.cswala.cswala package? And can i provide opening this fragment on selecting  ChipNavigationBar account-item?

**Comment by riturajjain2000** [comment]
> Hello! I can create this blank fragment. Should fragment be created in com.cswala.cswala package? And can i provide opening this fragment on selecting ChipNavigationBar account-item?

yes, for now, there will be just a blank fragment, and it will be opened with account-item, and create it in the same package

**Comment by viralkumar28** [comment]
Can you assign this issue to me..

**Comment by riturajjain2000** [comment]
@viralkumar28 Thanks for showing interest in this issue!
Let GSSOC begins and once I get to know the list of accepted participants for this project, I'll assign this issue accordingly.

**Comment by Anju1415** [comment]
interested

**Comment by riturajjain2000** [comment]
@viralkumar28 is working on it!
