### ISSUE TITLE
Add data for the backend

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/CSwala-android#48]
The database of this app is hosted on GitHub only as of now -

- https://github.com/CSwala/awesome-computer-science 
- https://github.com/CSwala/awesome-career-pages   

There are around 80 open issues in the above 2 repos.
We need to add as much data as we can.
This issue can be assigned to multiple participants at a time as is not at all related to any 1 tech stack. Participants from all sorts of technical expertise and background can contribute to this.

**Comment by fin1te** [comment]
I want to do this, please assign me. Thanks!

**Comment by namitgpta** [comment]
I want to work on this, please assign me ASAP. Thanks!!

**Comment by riturajjain2000** [comment]
Go ahead @namitgpta @fin1te

**Comment by jonathanalvares9009** [comment]
Can you assign me this issue?

**Comment by Rads1208** [comment]
I am interested. can you assign this to me?

**Comment by riturajjain2000** [comment]
> @riturajjain2000 , I think we should make REST-api for this purpose...
> I can make Rest API with Nodejs

Yes we have to do smthng like that only as there is no means of connecting GH repo as DB to android as I know , but this issue is  just for collecting data .

**Comment by riturajjain2000** [comment]
> I am interested. can you assign this to me?

Sure , go ahead !

**Comment by KapilYadav-dev** [comment]
> Yes we have to do smthng like that only as there is no means of connecting GH repo as DB to

Ooh Got it ...

**Comment by SanjayDevTech** [comment]
Can i work on this issue... Could you assign this?

**Comment by Khushi-24** [comment]
Can I also work on this?

**Comment by SanjayDevTech** [comment]
@riturajjain2000 we can close this issue for now ?!
