### ISSUE TITLE
Add Jobs/Internship Fragment

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/CSwala-android#5]
Add a blank fragment for this option, just as to provide the functionality of swapping screens as of now. Will add features later.

**Comment by vipozdn** [comment]
Hello! I can create this blank fragment. Should fragment be created in com.cswala.cswala package?

**Comment by riturajjain2000** [comment]
yes, for now, there will be just a blank fragment, and it will be opened with JOBHUNT, and create it in the same package

**Comment by GowthamGoush** [comment]
May I work on this issue as a participant of GSSoC '21?

**Comment by riturajjain2000** [comment]
> May I work on this issue as a participant of GSSoC '21?

sure go ahead!

**Comment by Anju1415** [comment]
can i work on this as a  GSSoc participant?

**Comment by riturajjain2000** [comment]
> can i work on this as a GSSoC participant?

@GowthamGoush is working on it ! Choose another issue or create one

**Comment by GowthamGoush** [comment]
Just to make sure, should the fragment be created with the name "JOBHUNT" with all characters in the capital?

**Comment by riturajjain2000** [comment]
It doesn't really matter , as all we want to have is a blank fragment which will be displayed when jonhunt from the navbar is clicked!

**Comment by GowthamGoush** [comment]
So I have made a switch statement for the fragment under onItemSelected listener and added empty cases for the rest of the fragments as well. Is that alright?

**Comment by riturajjain2000** [comment]
Yup , thats fine by me !
