### ISSUE TITLE
Google login not working for me

### ISSUE THREAD

**Issue by namitgpta** [CSwala/CSwala-android#50]
I installed the app on my phone through android studio by forking the project. It installed successfully without any issues on my Android 10 phone but when I open the app and login through Google, it doesn't show anything after that. Please help regarding this issue.
I have attached screenshot of Android studio also during the login process:
<img width="960" alt="Screenshot 2021-03-09 213605" src="https://user-images.githubusercontent.com/60420298/110500685-79101b00-811f-11eb-9bcc-90c24510e402.png">

**Comment by riturajjain2000** [comment]
Ok , its not working for me either , Go ahead to work on it !

**Comment by namitgpta** [comment]
Is the SHA fingerprint added in the project settings in the firebase - Your Apps section??

**Comment by Anju1415** [comment]
I would also like to work on this .

**Comment by iamvs-2002** [comment]
If no one else is working on it, kindly assign it to me.

**Comment by riturajjain2000** [comment]
> If no one else is working on it, kindly assign it to me.

@namitgpta is working on it ,choose another issue

**Comment by iamvs-2002** [comment]
> > If no one else is working on it, kindly assign it to me.
> 
> @namitgpta is working on it ,choose another issue

Alright!

**Comment by riturajjain2000** [comment]
They are both there!

**Comment by iamvs-2002** [comment]
> They are both there!

Ohh okay.

**Comment by fin1te** [comment]
Let me know when this is resolved.

**Comment by iamvs-2002** [comment]
@riturajjain2000 May I reopen this issue and work on it?

**Comment by riturajjain2000** [comment]
Its fixed !

**Comment by iamvs-2002** [comment]
> Its fixed !

Okay.
