### ISSUE TITLE
Update The Launcher Icon

### ISSUE THREAD

**Issue by Junaid55** [CSwala/CSwala-android#58]

**Comment by Junaid55** [comment]
Launcher icon is so simple so i want to add some aesthetic touch to it so assigned it to me.

**Comment by Junaid55** [comment]
do I again need to change the launcher icon and push it please tell me

**Comment by Junaid55** [comment]
i previously make a pr but you suggest me to first create an issue and assign it 
and thanks for assigning this issue to me

**Comment by riturajjain2000** [comment]
Just change the base branch from main to develop

**Comment by Junaid55** [comment]
I miskenly unassign myself please re assign me

**Comment by Junaid55** [comment]
Sir i alredy fix the issue do i need to close the issue

**Comment by riturajjain2000** [comment]
I dont think its fixed , as the PR is still open

**Comment by hemant2705** [comment]
What  is left to do regarding this issue?

**Comment by riturajjain2000** [comment]
Nothing has been done , you have to implement it fully

**Comment by Khushi-24** [comment]
@riturajjain2000 Can I work on this issue if no one is working on it?

**Comment by snehagarg-bit** [comment]
Can I work on this issue  ?
