### ISSUE TITLE
Add Community Fragment

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/CSwala-android#6]
Add a blank fragment for this option, just as to provide the functionality of swapping screens as of now. Will add features later.

**Comment by vipozdn** [comment]
I can create this Fragment. And can i provide opening this fragment on selecting ChipNavigationBar inbox-item?

**Comment by riturajjain2000** [comment]
yes, for now, there will be just a blank fragment

**Comment by viralkumar28** [comment]
I would like to contribute in this issue, would you assign this to me.

**Comment by riturajjain2000** [comment]
@viralkumar28 Thanks for showing interest in this issue!
Let GSSOC begins and once I get to know the list of accepted participants for this project, I'll assign this issue accordingly.

**Comment by riturajjain2000** [comment]
> @riturajjain2000 it's been a week. Can i take on this? Or can you assign me some other issue?

Wait I am opening new issues , plz look into them
