### ISSUE TITLE
Adding a Email Login Option 

### ISSUE THREAD

**Issue by Khushi-24** [CSwala/CSwala-android#60]
When we use Google and Facebook Login the code is needed to be updated after a period of time. Login with email can be a substitution for this problem(if the code is not updated at least there would be one option available through which the user can log in to the app).

**Comment by fin1te** [comment]
We can have this option simultaneously with the GitHub & Google login options imo, as it is comparatively more easy and efficient to login via a 3rd party than Email

**Comment by KapilYadav-dev** [comment]
@Khushi-24  will you design UI also for this or just simple UI with functioning...

**Comment by Khushi-24** [comment]
@KapilYadav-dev  Do you want to design UI ?

**Comment by fin1te** [comment]
@Khushi-24 I can design the UI, let me know if I can help out.

**Comment by KapilYadav-dev** [comment]
@Khushi-24  I can do XML part as well Figma part...
Let me know where can I help you...  :)

**Comment by tanishq-123** [comment]
If this issue is not resolved yet then i would like to take this one.

**Comment by hemant2705** [comment]
@Khushi-24 Are you still working upon it if yes how much more time you needed ,if no I want to take over it .

**Comment by codeankit10** [comment]
I am a GSSOC participant. Can I work in this issue?

**Comment by Khushi-24** [comment]
Yes, I am working on this issue. Sorry for the delay. I got a bit busy due to my exams and Project Presentation which just got completed Yesterday.
