### ISSUE TITLE
Adding a API and Fetch data

### ISSUE THREAD

**Issue by etamys** [CSwala/CSwala-android#62]
I think we need to Create a API . Where we can put list of YouTube channels or other Resources, Then we can fetch data From API.
it's Remove the burden of updating Resource list again and again , by Using API we have to just Update the list on server

**Comment by riturajjain2000** [comment]
> I think we need to Create a API . Where we can put list of YouTube channels or other Resources, Then we can fetch data From API.
> it's Remove the burden of updating Resource list again and again , by Using API we have to just Update the list on server

Yes we have to do smthng like that only as there is no means of connecting GH repo as DB to android as I know , but #48 issue is just for collecting data . Once it is added to the repo than we can add that to the server
