### ISSUE TITLE
Main Activity text does not fit for most current device sizes

### ISSUE THREAD

**Issue by fin1te** [CSwala/CSwala-android#65]
![image](https://user-images.githubusercontent.com/62439440/110784196-66b4ef00-828f-11eb-8e36-0ee54950cf62.png)

Texts in the bottom Navigation Bar does not fit the screen sizes for many currently used device sizes, I would like to fix this Issue by removing the text, making icons a little big and having them in centre, and add a Toaster for the option names on long press. this way the UI will look more clean and minimal, as well as users can see name of the menu when they long click any button.

**Please assign me this Issue, Thanks!**

**Comment by riturajjain2000** [comment]
How are you getting this error , as only explore should be written in text , rest should be only icons

![Screenshot_1615469608](https://user-images.githubusercontent.com/48384309/110795138-856db280-829c-11eb-8f2a-d5327318fbb8.png)


# Like this

**Comment by fin1te** [comment]
@riturajjain2000 
![image](https://user-images.githubusercontent.com/62439440/110814435-72b0a900-82af-11eb-9fdd-7b9b3efc34e0.png)
this is the main activity xml I see in my AS, 

I Fetched the develop branch and merged from upstream again, still I see this one

**Comment by riturajjain2000** [comment]
Did you run this on a physical device or not, as Studio typically is not compatible with external Libraries. So prefer running it on an emulator or physical device for UI testing!

**Comment by fin1te** [comment]
Since neither Google or GitHub login is working, I'm not able to check the main activity in Physical device / Emulator

**Comment by etamys** [comment]
please assign it to me i will fix it.

**Comment by fin1te** [comment]
> please assign it to me i will fix it.i Will make it responsive

@etamys which one of the above nav bar you see in yours?

**Comment by riturajjain2000** [comment]
> Since neither Google or GitHub login is working, I'm not able to check the main activity in Physical device / Emulator

for testing sake you can check it by making it the default activity

**Comment by fin1te** [comment]
> > Since neither Google or GitHub login is working, I'm not able to check the main activity in Physical device / Emulator
> 
> for testing sake you can check it by making it the default activity , just don't push them to GH

@riturajjain2000  but how will we edit it, if we need to edit it and can not see it in android studio

**Comment by riturajjain2000** [comment]
Why not , you can do anything that you want just like if logins were working , Im just asking to change Launcher activity in the `manisfest`  for testing sakes

**Comment by iamvs-2002** [comment]
If no one is working on this, kindly assign it to me.

**Comment by riturajjain2000** [comment]
First we have to verify if it really is a issue or not !

**Comment by iamvs-2002** [comment]
> First we have to verify if it really is a issue or not !

Okay, but I think it is and it can be avoided by using nested layouts.

**Comment by riturajjain2000** [comment]
Confirm it first using a small screen device

**Comment by iamvs-2002** [comment]
> Confirm it first using a small screen device

Done! 
Also, the solution I gave, i.e. nested layouts, it works now!

**Comment by riturajjain2000** [comment]
send a ss of small screen display having that issue !

**Comment by RashikaJoshi-777** [comment]
![Screenshot_20210315-153635 1](https://user-images.githubusercontent.com/75016031/111138139-97ee3180-85a5-11eb-898a-853e43567723.png)

**Comment by RashikaJoshi-777** [comment]
it's working perfectly on small screen devices

**Comment by iamvs-2002** [comment]
> it's working perfectly on small screen devices

I see, it certainly does.
I got it now, I actually too just worked on the layout for the Pixel 3 and hence felt it's an error. 
I tried running it on the Pixel, Nexus 6, and Pixel 4XL emulators, it works fine.

**Comment by riturajjain2000** [comment]
ok , then I dont see a point for this issue to remain open
