### ISSUE TITLE
Add Logout button to profile fragment

### ISSUE THREAD

**Issue by GowthamGoush** [CSwala/CSwala-android#67]
<div align="center">
<h4>The logout textview in the main activity is located right in the centre of the screen which hinders the visibility of the contents inside the fragments that are associated with the navbar. </h4>
<h4>I prefer to have a floating action button on the top left of the screen so that it becomes compact and provides less hinderence. Also switching to any other view/view-group will be a better option.</h4>
<img src="https://user-images.githubusercontent.com/63305824/110826795-74806980-82bb-11eb-817b-8fe43e42c3c9.png" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="200" height="400" />
</div>

**Comment by GowthamGoush** [comment]
Mentors, can you leave any suggestion for this issue?

**Comment by riturajjain2000** [comment]
Remove  the logout text from the main activity and add it to profile frag as a button

**Comment by GowthamGoush** [comment]
Is the profile fragment been added?

**Comment by riturajjain2000** [comment]
Not yet, you can add it if you want , just get that issue assigned to yourself

**Comment by GowthamGoush** [comment]
It seems like already someone is working on it. Shall I wait until it added, or shall I create a logout button inside mainactivity that displays only on clicking the profile?

**Comment by riturajjain2000** [comment]
Please wait until its added

**Comment by GowthamGoush** [comment]
In issue #87, you have mentioned a few more things that need to be accomplished. So could you mention that here again so that I can add/fix that within this issue?

**Comment by riturajjain2000** [comment]
No additional changes , you have to remove logout text from main activity and add it to profile fragment
