### ISSUE TITLE
Tech Stack Update ( LOGO add ) 

### ISSUE THREAD

**Issue by rohank2502** [CSwala/CSwala-android#68]
I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!

**Comment by riturajjain2000** [comment]
In the readme ??

**Comment by rohank2502** [comment]
> 
> 
> In the readme ??

Yes !!

**Comment by riturajjain2000** [comment]
Ok go for it!

**Comment by rohank2502** [comment]
Thanks !!
