### ISSUE TITLE
Create landscape variation for login activity

### ISSUE THREAD

**Issue by GowthamGoush** [CSwala/CSwala-android#74]
<div align = "center">
<h3> Some view elements get messed or not visible upon rotation </h3>

This issue is more common in low-resolution mobile devices.
Adding landscape variation would enhance the user experience.

<img src="https://user-images.githubusercontent.com/63305824/111024378-7e61b400-8404-11eb-8915-ee89f128d1ff.png" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="400" height="200" />
</div>

**Comment by riturajjain2000** [comment]
We are going to have a login using email button also , so I'll suggest doing this after that is added

**Comment by jonathanalvares9009** [comment]
@riturajjain2000 can I work on this issue?

**Comment by viralkumar28** [comment]
Can I work on this issue?
