### ISSUE TITLE
App crashing on start-up

### ISSUE THREAD

**Issue by mukul2310** [CSwala/CSwala-android#8]
**_App is crashing on starting the app._**

Error on Android Studio

![image](https://user-images.githubusercontent.com/44321379/108733455-88566c80-7554-11eb-9663-b39bec6411ca.png)

**Comment by mukul2310** [comment]
solved with PR #9

**Comment by riturajjain2000** [comment]
Hi @mukul2310 , No such error is coming , plz sync your fork with the latest main branch . And if the error is still there , plz discuss it on the discord server !!

**Comment by riturajjain2000** [comment]
I have reformatted code and added proper naming, so closing this as this is not relevant now!
