### ISSUE TITLE
Create landscape variation for main activity

### ISSUE THREAD

**Issue by GowthamGoush** [CSwala/CSwala-android#92]
<div align = "center">
<h3> Adding landscape variation eliminates view elements getting messed or becoming inaccessible upon rotation </h3>

This issue is more common in low-resolution mobile devices.
Adding landscape variation would enhance the user experience.
This issue is similar to #74 

</div>

**Comment by riturajjain2000** [comment]
Not needed as of now , as we have to decide the working of fragments also , so do it after that

**Comment by GowthamGoush** [comment]
Yeah sure

**Comment by GowthamGoush** [comment]
Shall I work on this now?

**Comment by GowthamGoush** [comment]
Should I reduce the size of the navbar for landscape variation? If so, then can you share the exact size I should follow.

**Comment by riturajjain2000** [comment]
See if you can move the navbar from bottom to left side
