### ISSUE TITLE
Enable progress dialog while logging in

### ISSUE THREAD

**Issue by GowthamGoush** [CSwala/CSwala-android#93]
<div align = "center">
<h3> Enhances user experience while logging in. </h3>
Add progress dialog to the following login options.
<br>
         ⦿ Google 
         ⦿ Github 
         ⦿ Email 
</div>

**Comment by codeankit10** [comment]
I am a GSSOC participant. Can I work in this issue?

**Comment by GowthamGoush** [comment]
I'm actually working on this issue. I believe this is closed by mistake since the email login feature is yet to be implemented.
