### ISSUE TITLE
Basic Refactoring Required

### ISSUE THREAD

**Issue by hemant2705** [CSwala/CSwala-android#94]
As many people are contributing it, will be good if we can refactor our code into few packages like
1. Common - Having Main Activity ,Login Activity ,OTP verification , splash screen and all common items.
2. Fragments - Having all the frames and fragments under one package

Please Assign this to me and mark down accordingly.

**Comment by riturajjain2000** [comment]
I'll suggest having category as Activities  rather than `Common`
