### ISSUE TITLE
Creating and implementing hackfeed fragment.

### ISSUE THREAD

**Issue by ayushman999** [CSwala/CSwala-android#97]
I would like to work on the Hackfeed fragment.
I'll create a hackfeed fragment and add one recycler view in it where the admin can post different articles and when clicked on it will open an activity where the detailed article will be present. I'll use an image, title, and a small description about the feeds with a like button as the basic patterns of the recyclerview. This is my idea about the hackfeed and if you are looking for more functionality in it then please do comment on it.

**Comment by riturajjain2000** [comment]
discuss the features on Discord
